name: 'Shan&Shay'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4195747319608927
title: 'Shan & Shay'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd900'
    - '#013cb0'
    - '#87a8da'
    - '#f8e673'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
