name: 'Shan&Shay'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4195747319608927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd900'
    - '#013cb0'
    - '#87a8da'
    - '#f8e673'
  brandStrength: 0.5
  lightness: 0.24333025701344013
  saturation: 0.39455465553328395
  rhythmicContrast: 0.6162023628130555
purpose: []
